name: CI (Backend)

on:
  push:
    branches: [master]
    paths:
      - backend/**
  pull_request:
    branches: [master]
    paths:
      - backend/**
  workflow_dispatch:

jobs:  
  test:
    defaults:
      run:
        working-directory: ./backend

    name: Run Tests (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint
